name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v2.1.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        run: ./gradlew check
      - name: Configure credentials
        run: |
          mkdir -p $HOME/.gradle
          touch $HOME/.gradle/gradle.properties
          chmod 0600 $HOME/.gradle/gradle.properties
          printf -- "---\ngradle.publish.key=${GRADLE_PUBLISH_KEY}\ngradle.publish.secret=${GRADLE_PUBLISH_SECRET}" > $HOME/.gradle/gradle.properties
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      - name: Publish
        run: ./gradlew publishPlugins
